import { NextRequest, NextResponse } from 'next/server';
import fs from 'fs';
import path from 'path';

// ============================================================================
// Types
// ============================================================================

interface PageContext {
  route: string;
  title: string;
  purpose: string;
  audience: 'public' | 'staff' | 'admin';
  steps?: string[];
  tips?: string[];
  features?: string[];
  routePattern?: string;
  routeParams?: string[];
  permissions?: string[];
  relatedPages?: string[];
  troubleshooting?: string[];
  autoGenerated: boolean;
  lastUpdated: string;
}

// ============================================================================
// Helper Functions
// ============================================================================

function getContextsFilePath(): string {
  return path.join(process.cwd(), 'public', 'page-contexts.json');
}

function loadContexts(): Record<string, PageContext> {
  try {
    const filePath = getContextsFilePath();
    const content = fs.readFileSync(filePath, 'utf-8');
    return JSON.parse(content);
  } catch (error) {
    console.error('Failed to load page contexts:', error);
    return {};
  }
}

function matchDynamicRoute(route: string, contexts: Record<string, PageContext>): PageContext | null {
  // Handle dynamic routes like /admin/service-requests/123
  for (const [pattern, context] of Object.entries(contexts)) {
    if (pattern.includes(':')) {
      const patternParts = pattern.split('/');
      const routeParts = route.split('/');

      if (patternParts.length !== routeParts.length) continue;

      const matches = patternParts.every((part, i) =>
        part.startsWith(':') || part === routeParts[i]
      );

      if (matches) {
        return { ...context, route };
      }
    }
  }
  return null;
}

// ============================================================================
// API Handler
// ============================================================================

export async function GET(request: NextRequest) {
  const { searchParams } = new URL(request.url);
  const route = searchParams.get('route');

  const contexts = loadContexts();

  // If no route specified, return all contexts
  if (!route) {
    return NextResponse.json(
      {
        totalPages: Object.keys(contexts).length,
        pages: contexts,
      },
      {
        headers: {
          'Cache-Control': 'public, max-age=3600, s-maxage=3600',
          'Access-Control-Allow-Origin': '*',
        },
      }
    );
  }

  // Normalize route
  const normalizedRoute = route.startsWith('/') ? route : `/${route}`;

  // Try exact match first
  let context = contexts[normalizedRoute];

  // Try dynamic route matching
  if (!context) {
    context = matchDynamicRoute(normalizedRoute, contexts);
  }

  // Return found context or generate fallback
  if (context) {
    return NextResponse.json(context, {
      headers: {
        'Cache-Control': 'public, max-age=3600, s-maxage=3600',
        'Access-Control-Allow-Origin': '*',
      },
    });
  }

  // Fallback for unknown routes
  return NextResponse.json(
    {
      route: normalizedRoute,
      title: 'GEA Portal Page',
      purpose: 'Government of Grenada Enterprise Architecture Portal',
      audience: 'public',
      autoGenerated: true,
      lastUpdated: new Date().toISOString(),
    },
    {
      headers: {
        'Cache-Control': 'public, max-age=300',
        'Access-Control-Allow-Origin': '*',
      },
    }
  );
}
