openapi: 3.1.0
info:
  title: GEA Portal - Grievances API
  description: Query individual grievance/complaint records
  version: 1.0.0

servers:
  - url: https://gea.gov.gd
    description: Production

security:
  - ApiKeyAuth: []

paths:
  /api/external/grievances:
    get:
      operationId: getGrievances
      summary: Query grievance records
      description: |
        Retrieve individual grievance/complaint records with filtering.
        PII fields (name, email, phone) are automatically masked.
        Use for: "Show open grievances", "List complaints for Ministry X"
      parameters:
        - name: status
          in: query
          description: Filter by grievance status
          schema:
            type: string
            enum: [open, in_progress, resolved, closed]
        - name: entity_id
          in: query
          description: Filter by entity ID
          schema:
            type: string
            example: DEPT-001
        - name: entity_name
          in: query
          description: Fuzzy search by entity name (case-insensitive)
          schema:
            type: string
            example: immigration
        - name: service_id
          in: query
          description: Filter by service ID
          schema:
            type: string
        - name: service_name
          in: query
          description: Fuzzy search by service name
          schema:
            type: string
            example: work permit
        - name: limit
          in: query
          description: Max records (default 50, max 100)
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 50
        - name: offset
          in: query
          description: Pagination offset
          schema:
            type: integer
            minimum: 0
            default: 0
      responses:
        '200':
          description: List of grievances
          content:
            application/json:
              schema:
                type: object
                required: [success, data, pagination, meta]
                properties:
                  success:
                    type: boolean
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        grievance_number:
                          type: string
                          example: GRV-2025-001
                        subject:
                          type: string
                        status:
                          type: string
                          enum: [open, in_progress, resolved, closed]
                        submitter_category:
                          type: string
                          nullable: true
                        submitter_name:
                          type: string
                          description: "Masked (e.g., J*** D***)"
                        submitter_email:
                          type: string
                          description: "Masked (e.g., j***@example.com)"
                        submitter_phone:
                          type: string
                          nullable: true
                          description: "Masked (e.g., ***-1234)"
                        incident_date:
                          type: string
                          format: date
                          nullable: true
                        assigned_to:
                          type: string
                          nullable: true
                        created_at:
                          type: string
                          format: date-time
                        updated_at:
                          type: string
                          format: date-time
                        resolved_at:
                          type: string
                          format: date-time
                          nullable: true
                        closed_at:
                          type: string
                          format: date-time
                          nullable: true
                        entity:
                          type: object
                          properties:
                            id:
                              type: string
                            name:
                              type: string
                        service:
                          type: object
                          properties:
                            id:
                              type: string
                            name:
                              type: string
                  pagination:
                    type: object
                    properties:
                      total:
                        type: integer
                      limit:
                        type: integer
                      offset:
                        type: integer
                      has_more:
                        type: boolean
                  meta:
                    type: object
                    properties:
                      filters:
                        type: object
                      generated_at:
                        type: string
                        format: date-time
        '400':
          description: Invalid status parameter
        '401':
          description: Invalid or missing API key

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
