openapi: 3.1.0
info:
  title: GEA Portal - Service Requirements API
  description: Get document requirements for EA services
  version: 1.0.0

servers:
  - url: https://gea.abhirup.app
    description: Production

security:
  - ApiKeyAuth: []

paths:
  /api/external/services/requirements:
    get:
      operationId: getServiceRequirements
      summary: Get service document requirements
      description: |
        Retrieve the list of required documents for a specific EA service.
        Use for: "What docs do I need for work permit?", "Show birth certificate requirements"
      parameters:
        - name: service_id
          in: query
          required: true
          description: |
            Service ID (format: SVC-XXX-NNN).
            Common IDs: SVC-LBR-001 (Work Permit), SVC-REG-001 (Birth Certificate), SVC-DIG-001 (EA Portal Support)
            To find more IDs: GET /api/external/dashboard?include=services
          schema:
            type: string
            example: SVC-LBR-001
      responses:
        '200':
          description: Service details with document requirements
          content:
            application/json:
              schema:
                type: object
                required: [success, data, meta]
                properties:
                  success:
                    type: boolean
                  data:
                    type: object
                    properties:
                      service:
                        type: object
                        properties:
                          id:
                            type: string
                          name:
                            type: string
                          category:
                            type: string
                          description:
                            type: string
                          is_active:
                            type: boolean
                          entity:
                            type: object
                            properties:
                              id:
                                type: string
                              name:
                                type: string
                      requirements:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: integer
                            filename:
                              type: string
                              description: Display name of the document
                            file_extension:
                              type: string
                              description: Expected format (pdf, docx, xlsx)
                            is_mandatory:
                              type: boolean
                            description:
                              type: string
                              nullable: true
                      summary:
                        type: object
                        properties:
                          total:
                            type: integer
                          mandatory:
                            type: integer
                          optional:
                            type: integer
                  meta:
                    type: object
                    properties:
                      generated_at:
                        type: string
                        format: date-time
              example:
                success: true
                data:
                  service:
                    id: SVC-LBR-001
                    name: Work Permit Application
                    category: business_and_commerce
                    description: Apply for a work permit for foreign nationals to work in Grenada.
                    is_active: true
                    entity:
                      id: DEP-012
                      name: Department of Labour
                  requirements:
                    - id: 212
                      filename: Work Permit Application Form
                      file_extension: pdf
                      is_mandatory: true
                      description: Application for work permit for non-nationals.
                    - id: 213
                      filename: Employment Contract or Offer Letter
                      file_extension: pdf
                      is_mandatory: true
                      description: Evidence of employment offer from local employer.
                  summary:
                    total: 2
                    mandatory: 2
                    optional: 0
                meta:
                  generated_at: "2025-12-18T10:30:00Z"
        '400':
          description: Missing service_id parameter
          content:
            application/json:
              example:
                success: false
                error: "service_id query parameter is required"
        '401':
          description: Invalid or missing API key
        '404':
          description: Service not found
          content:
            application/json:
              example:
                success: false
                error: "Service not found: invalid-id"

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
