// GET /api/ai-agents/download?agentId=...&path=...&filename=...
// Streams a binary output (PDF, Word, image, etc.) generated by an agent
// job back to the browser, attaching the agent's bearer token server-side.
//
// `path` must be the relative download path returned by the agent's
// invoke response, e.g.
//   /api/agent-bots/file-testing-agent/jobs/<jobId>/outputs/<outputId>/download
// The proxy resolves the absolute URL against the agent's configured
// endpoint origin so the browser never sees the token or the upstream host.

import { NextRequest, NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth';
import { getAgentById, getAgentToken } from '@/lib/ai-agents';

export const dynamic = 'force-dynamic';
export const maxDuration = 60;

export async function GET(req: NextRequest) {
  const session = await getServerSession(authOptions);
  if (!session) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const { searchParams } = new URL(req.url);
  const agentId = searchParams.get('agentId');
  const path = searchParams.get('path');
  const filename = searchParams.get('filename') || 'download';

  if (!agentId) {
    return NextResponse.json({ error: 'agentId is required' }, { status: 400 });
  }
  if (!path) {
    return NextResponse.json({ error: 'path is required' }, { status: 400 });
  }

  const agent = await getAgentById(agentId);
  if (!agent) {
    return NextResponse.json({ error: `Unknown agent: ${agentId}` }, { status: 404 });
  }

  const token = await getAgentToken(agent);
  if (!token) {
    return NextResponse.json(
      { error: `Bearer token not configured for agent "${agent.name}"` },
      { status: 500 },
    );
  }

  // Resolve the absolute upstream URL. Accept either an absolute URL (must
  // share the same origin as the agent endpoint) or a relative path.
  let upstreamUrl: string;
  try {
    const base = new URL(agent.endpoint);
    if (path.startsWith('http://') || path.startsWith('https://')) {
      const candidate = new URL(path);
      if (candidate.origin !== base.origin) {
        return NextResponse.json(
          { error: 'Download path must share the agent endpoint origin' },
          { status: 400 },
        );
      }
      upstreamUrl = candidate.toString();
    } else {
      upstreamUrl = new URL(path, base).toString();
    }
  } catch {
    return NextResponse.json({ error: 'Invalid path' }, { status: 400 });
  }

  let upstreamRes: Response;
  try {
    upstreamRes = await fetch(upstreamUrl, {
      method: 'GET',
      headers: { Authorization: `Bearer ${token}` },
    });
  } catch (err) {
    const msg = err instanceof Error ? err.message : 'Network error';
    return NextResponse.json({ error: `Upstream request failed: ${msg}` }, { status: 502 });
  }

  if (!upstreamRes.ok) {
    const body = await upstreamRes.text().catch(() => '');
    return NextResponse.json(
      {
        error: `Agent returned HTTP ${upstreamRes.status}`,
        upstreamStatus: upstreamRes.status,
        upstreamBody: body.slice(0, 2000),
      },
      { status: 502 },
    );
  }

  const contentType = upstreamRes.headers.get('content-type') || 'application/octet-stream';
  const contentLength = upstreamRes.headers.get('content-length');
  const inline = (searchParams.get('inline') || '').toLowerCase() === 'true';
  const disposition = inline
    ? `inline; filename="${filename.replace(/"/g, '')}"`
    : `attachment; filename="${filename.replace(/"/g, '')}"`;

  const headers: Record<string, string> = {
    'Content-Type': contentType,
    'Content-Disposition': disposition,
    'Cache-Control': 'private, no-store',
  };
  if (contentLength) headers['Content-Length'] = contentLength;

  return new NextResponse(upstreamRes.body, { status: 200, headers });
}
